# Generated by Django 2.2.1 on 2019-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190529_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('T-Shirts', 'T-Shirts'), ('Glasses', 'Glasses'), ('Shoes', 'Shoes'), ('Phone', 'Phone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Glasses', 'Glasses'), ('Shoes', 'Shoes'), ('Phone', 'Phone')], max_length=20),
        ),
    ]
