# Generated by Django 2.1.7 on 2019-05-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Lifestyle', 'Lifestyle')], max_length=20)),
                ('sub_category', models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Glasses', 'Glasses'), ('Shoes', 'Shoes')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
