# Generated by Django 2.1.7 on 2019-05-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.FileField(blank=True, upload_to='banner_images/'),
        ),
    ]
